inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2

Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false
  SupportedStyles:
    - ruby19
    - hash_rockets

# Do not limit line length so much
Layout/LineLength:
    Max: 385

Metrics/MethodLength:
  Max: 20
